### ISSUE TITLE
Angular ng build --prod error

### ISSUE THREAD

**Issue by gpulido** [kuzzleio/sdk-javascript#472] opened 2019-12-04 11:53 UTC
Build compilation for production fails when using the kuzzle-sdk in an angular project
## Expected Behavior
Correct build for production

## Possible Solution
for the version error substitute 
```
require('../package').version
```
by 
```
require('../package.json').version
```

## Steps to Reproduce
1. install kuzzle sdk into a angular project:
```
npm i kuzzle-sdk
```
2. Run ng build --prod

3. Following error is raised:
```ERROR in ./node_modules/kuzzle-sdk/src/Kuzzle.js
Module not found: Error: Can't resolve '../package' in 'E:\tmp\archery-annotation-web\archery-annotation\node_modules\kuzzle-sdk\src'
resolve '../package' in 'E:\tmp\archery-annotation-web\archery-annotation\node_modules\kuzzle-sdk\src'
  using description file: E:\tmp\archery-annotation-web\archery-annotation\node_modules\kuzzle-sdk\package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
```
If I change the following llines into kuzzle.js:
```
    this.sdkVersion = typeof SDKVERSION === 'undefined'
      ? require('../package').version
      : SDKVERSION;
```
to be 
```
    this.sdkVersion = typeof SDKVERSION === 'undefined'
      ? require('../package.json').version
      : SDKVERSION;
```
The error is not raised.

After that error two other errors are being raised:
```
ERROR in ./node_modules/min-req-promise/src/index.js
Module not found: Error: Can't resolve 'http' in 'E:\tmp\archery-annotation-web\archery-annotation\node_modules\min-req-promise\src'
resolve 'http' in 'E:\tmp\archery-annotation-web\archery-annotation\node_modules\min-req-promise\src'
  Parsed request is a module
  using description file: E:\tmp\archery-annotation-web\archery-annotation\node_modules\min-req-promise\package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
```
And another for https.
Those errors probably are just by the library min-req-promise that kuzzle is trying to use.

Kuzzle version: 2.0.0
Node.js version:12.10.0
SDK version:7.0.1
Angular version: 8.3.14

UPDATE:
The http / https errors from min-req-promise are being caused because those modules are Node.js core that can't be loaded on a browser.

UPDATE2:
Reviewing the kuzzle-js code it only try to load the min-req-promise when is not in a browser. The problem with angular is kuzzle-sdk declaring the dependency from min-req-promise so it adds the node module and is not capable of droping it from the build prod.

**Comment by gpulido** [comment] 2019-12-04 14:21
After more investigation I think I found the real issue but I don't know how to solve.

1. Regading the "package version" The solution seems to be to apply the ```require('../package.json').version``` 
2. The other problem is more tricky. Kuzzle-sdk is declaring a dependency to 'min-req-promise' to be used in case it is not running in a browser. Although angular won't use it as it is running on a browser, the build process is trying to add and use it and is raising the http / https error.
In order to make it work I had to comment the code on the kuzzle-sdk that just check if it is not ina browser. 
One solution is to not include the dependency directly and just explain that in case it is  use in node enviroments, it has to be manually installed, and make a check on the code to be sure that the library is loaded before trying to "require" it.
The other solution is create a "browser-kuzzle-sdk" specific package without the offending library but that would mean to keep two repos sync.
Maybe there is a way to "inject" the dependency in case is needed...

**Comment by Aschen** [comment] 2019-12-05 10:25
Hello @gpulido,

Is it normal that Angular try to resolve modules requirement when building the application?
Can you provide us an easy way to reproduce the problem so we can try to fix it ?

**Comment by scottinet** [comment] 2019-12-05 10:26
Hi,

You probably need to use the browser-version of the JS SDK, built&available in the `dist/` directory of the SDK (`dist/kuzzle.js`)

**Comment by gpulido** [comment] 2019-12-05 10:42
Hello,
Ok, just trying to figure out how to tell angular / package manager to pick the dist version.

**Comment by rolljee** [comment] 2023-05-15 06:31
Closing due to time. feel free to reopen if it still happen

**Closed by rolljee** 2023-05-15 06:31 UTC
