### ISSUE TITLE
LOGIN : undefined is not an object (evaluating 'this._url.endsWith') passing JS SDK 7.8.2 to 7.8.3

### ISSUE THREAD

**Issue by iotools-systems** [kuzzleio/sdk-javascript#703] opened 2022-07-25 10:16 UTC
After trying to update kuzzle-sdk currently in version 7.8.2 to a higher version, the function kuzzle.auth.login('local', {credentials}) gives the following error: [TypeError: undefined is not an object (evaluating 'this._url.endsWith')].

The SDK is created with a protocol HTTP or WebSocket and Kuzzle is running in local (port: 7512, ssl: false)

## Usage

```
try {
  await kuzzle.connect();
  const user = await kuzzle.auth.login('local', {
           username: 'MyUsername',
            password: 'MyPassword',
  });
  console.log(user);
} catch (error) {
      console.log({error});
}
```

## Context (Environment)

Kuzzle version: 2.17.5
Node.js version: 16.14.2
SDK version: 7.8.2 and try to update to 7.8.3 or higher
React-native: 0.64.3
React: 17.0.1

**Comment by Aschen** [comment] 2022-11-10 19:40
Hi @iotools-systems 

Is this bug still present in the latest version of the SDK?

**Comment by itishermann** [comment] 2023-01-02 08:16
hi, i'm facing the same issue with the latest version
here is a minimal reproductible example https://snack.expo.dev/@itishermann/kuzzle-playground?platform=ios

**Comment by Shiranuit** [comment] 2023-01-02 14:49
Thank you @itishermann, I was able to quickly identify the root cause of the issue thanks to your playground example.
This issue should hopefully be fixed in the next release of the SDK, see PR https://github.com/kuzzleio/sdk-javascript/pull/718.

**Closed** 2023-05-14 20:12 UTC
Labels: bug
